@baseUrl = http://localhost:3000

### Listar libros
GET {{baseUrl}}/api/libros

### Sólo los disponibles
GET {{baseUrl}}/api/libros?disponible=true

### Un libro
GET {{baseUrl}}/api/libros/1

### Un libro que no existe → 404
GET {{baseUrl}}/api/libros/99

### Eliminar un libro que no existe
DELETE {{baseUrl}}/api/libros/99


### Listar autores
GET {{baseUrl}}/api/autores

### Un autor
GET {{baseUrl}}/api/autores/1

### Un autor que no existe → 404
GET {{baseUrl}}/api/autores/99

### Eliminar un autor
DELETE {{baseUrl}}/api/autores/1

### Crear un autor
POST http://localhost:3000/api/autores
Content-Type: application/json

{
  "nombre": "Isabel Allende",
  "nacionalidad": "Chile"
}
###